name: smartcalc
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0' # แนะนำให้ใช้ช่วงเวอร์ชันที่กว้างขึ้น

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # -- dependencies ที่เพิ่มเข้ามาให้ตรงกับโค้ด --
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.12.0
  math_expressions: ^2.6.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.0
  # -----------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true